language: elixir
elixir:
  - 1.4.5
  - 1.9.4
before_script:
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip -d protoc protoc-3.6.1-linux-x86_64.zip
  - export PATH=$PWD/protoc/bin/:$PATH
env:
  - MIX_ENV=test
script: mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    - alexandre.hamez+travis@easymile.com
