language: elixir
matrix:
  include:
    - elixir: 1.6
      otp_release: 21.0
    - elixir: 1.7
      otp_release: 22.0
    - elixir: 1.8
      otp_release: 22.0
    - elixir: 1.9
      otp_release: 22.0
    - elixir: 1.10
      otp_release: 22.0
before_script:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/protoc-3.12.0-linux-x86_64.zip
  - unzip -d protoc protoc-3.12.0-linux-x86_64.zip
  - export PATH=$PWD/protoc/bin/:$PATH
  - wget https://github.com/EasyMile/protox/releases/download/0.20.0/conformance-linux-x86_64.zip
  - unzip conformance-linux-x86_64.zip
env:
  - MIX_ENV=test PROTOBUF_CONFORMANCE_RUNNER=./conformance/conformance-test-runner LD_LIBRARY_PATH=./conformance/.libs
script:
  - mix dialyzer
  - mix coveralls.travis --include conformance
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    - alexandre.hamez+travis@easymile.com
cache:
  directories:
    - priv/plts
