language: elixir
elixir:
  - 1.3.4
  - 1.4.1
otp_release:
  - 18.2
  - 18.3
  - 19.1
  - 19.2
before_script:
  - wget https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
  - unzip -d protoc protoc-3.2.0-linux-x86_64.zip
  - export PATH=$PWD/protoc/bin/:$PATH
env:
  - MIX_ENV=test
script: mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    - alexandre.hamez+travis@easymile.com
